///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductGetResponseDataProducts {
/*
{
  "prodImage": "https://www.daikinindia.com/sites/default/files/air-conditioners.png",
  "prodId": "1",
  "prodCode": "8903287017032",
  "barCode": "1234,5678,9012",
  "prodName": "AIR, CONDITIONER IACS12AK3TC",
  "UOM": "Nos",
  "unit_id": "1",
  "prod_combo": "0",
  "is_focused": "no",
  "group_ids": "180,177",
  "category_ids": "1",
  "unit_from_value": "0.50",
  "unit_to_value": "1.00",
  "uom_alternate_name": "Kgs",
  "uom_alternate_id": "2",
  "under_warranty": "no",
  "groupId": "180",
  "catId": "1",
  "prodHsnId": "",
  "prodHsnCode": "",
  "prodShortName": "",
  "prodPrice": "28500.00",
  "prodMrp": "28500.00",
  "prodBuy": "28500.00",
  "prodSell": "28500.00",
  "prodFreeItem": "",
  "prodRkPrice": "28500.00"
}
*/

  String? prodImage;
  String? prodId;
  String? prodCode;
  String? barCode;
  String? prodName;
  String? UOM;
  String? unitId;
  String? prodCombo;
  String? isFocused;
  String? groupIds;
  String? categoryIds;
  String? unitFromValue;
  String? unitToValue;
  String? uomAlternateName;
  String? uomAlternateId;
  String? underWarranty;
  String? groupId;
  String? catId;
  String? prodHsnId;
  String? prodHsnCode;
  String? prodShortName;
  String? prodPrice;
  String? prodMrp;
  String? prodBuy;
  String? prodSell;
  String? prodFreeItem;
  String? prodRkPrice;

  ProductGetResponseDataProducts({
    this.prodImage,
    this.prodId,
    this.prodCode,
    this.barCode,
    this.prodName,
    this.UOM,
    this.unitId,
    this.prodCombo,
    this.isFocused,
    this.groupIds,
    this.categoryIds,
    this.unitFromValue,
    this.unitToValue,
    this.uomAlternateName,
    this.uomAlternateId,
    this.underWarranty,
    this.groupId,
    this.catId,
    this.prodHsnId,
    this.prodHsnCode,
    this.prodShortName,
    this.prodPrice,
    this.prodMrp,
    this.prodBuy,
    this.prodSell,
    this.prodFreeItem,
    this.prodRkPrice,
  });
  ProductGetResponseDataProducts.fromJson(Map<String, dynamic> json) {
    prodImage = json['prodImage']?.toString();
    prodId = json['prodId']?.toString();
    prodCode = json['prodCode']?.toString();
    barCode = json['barCode']?.toString();
    prodName = json['prodName']?.toString();
    UOM = json['UOM']?.toString();
    unitId = json['unit_id']?.toString();
    prodCombo = json['prod_combo']?.toString();
    isFocused = json['is_focused']?.toString();
    groupIds = json['group_ids']?.toString();
    categoryIds = json['category_ids']?.toString();
    unitFromValue = json['unit_from_value']?.toString();
    unitToValue = json['unit_to_value']?.toString();
    uomAlternateName = json['uom_alternate_name']?.toString();
    uomAlternateId = json['uom_alternate_id']?.toString();
    underWarranty = json['under_warranty']?.toString();
    groupId = json['groupId']?.toString();
    catId = json['catId']?.toString();
    prodHsnId = json['prodHsnId']?.toString();
    prodHsnCode = json['prodHsnCode']?.toString();
    prodShortName = json['prodShortName']?.toString();
    prodPrice = json['prodPrice']?.toString();
    prodMrp = json['prodMrp']?.toString();
    prodBuy = json['prodBuy']?.toString();
    prodSell = json['prodSell']?.toString();
    prodFreeItem = json['prodFreeItem']?.toString();
    prodRkPrice = json['prodRkPrice']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['prodImage'] = prodImage;
    data['prodId'] = prodId;
    data['prodCode'] = prodCode;
    data['barCode'] = barCode;
    data['prodName'] = prodName;
    data['UOM'] = UOM;
    data['unit_id'] = unitId;
    data['prod_combo'] = prodCombo;
    data['is_focused'] = isFocused;
    data['group_ids'] = groupIds;
    data['category_ids'] = categoryIds;
    data['unit_from_value'] = unitFromValue;
    data['unit_to_value'] = unitToValue;
    data['uom_alternate_name'] = uomAlternateName;
    data['uom_alternate_id'] = uomAlternateId;
    data['under_warranty'] = underWarranty;
    data['groupId'] = groupId;
    data['catId'] = catId;
    data['prodHsnId'] = prodHsnId;
    data['prodHsnCode'] = prodHsnCode;
    data['prodShortName'] = prodShortName;
    data['prodPrice'] = prodPrice;
    data['prodMrp'] = prodMrp;
    data['prodBuy'] = prodBuy;
    data['prodSell'] = prodSell;
    data['prodFreeItem'] = prodFreeItem;
    data['prodRkPrice'] = prodRkPrice;
    return data;
  }
}

class ProductGetResponseData {
/*
{
  "products": [
    {
      "prodImage": "https://www.daikinindia.com/sites/default/files/air-conditioners.png",
      "prodId": "1",
      "prodCode": "8903287017032",
      "barCode": "1234,5678,9012",
      "prodName": "AIR, CONDITIONER IACS12AK3TC",
      "UOM": "Nos",
      "unit_id": "1",
      "prod_combo": "0",
      "is_focused": "no",
      "group_ids": "180,177",
      "category_ids": "1",
      "unit_from_value": "0.50",
      "unit_to_value": "1.00",
      "uom_alternate_name": "Kgs",
      "uom_alternate_id": "2",
      "under_warranty": "no",
      "groupId": "180",
      "catId": "1",
      "prodHsnId": "",
      "prodHsnCode": "",
      "prodShortName": "",
      "prodPrice": "28500.00",
      "prodMrp": "28500.00",
      "prodBuy": "28500.00",
      "prodSell": "28500.00",
      "prodFreeItem": "",
      "prodRkPrice": "28500.00"
    }
  ]
}
*/

  List<ProductGetResponseDataProducts?>? products;

  ProductGetResponseData({
    this.products,
  });
  ProductGetResponseData.fromJson(Map<String, dynamic> json) {
    if (json['products'] != null) {
      final v = json['products'];
      final arr0 = <ProductGetResponseDataProducts>[];
      v.forEach((v) {
        arr0.add(ProductGetResponseDataProducts.fromJson(v));
      });
      products = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (products != null) {
      final v = products;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['products'] = arr0;
    }
    return data;
  }
}

class ProductGetResponse {
/*
{
  "status": true,
  "message": "Products returned successfull",
  "data": {
    "products": [
      {
        "prodImage": "https://www.daikinindia.com/sites/default/files/air-conditioners.png",
        "prodId": "1",
        "prodCode": "8903287017032",
        "barCode": "1234,5678,9012",
        "prodName": "AIR, CONDITIONER IACS12AK3TC",
        "UOM": "Nos",
        "unit_id": "1",
        "prod_combo": "0",
        "is_focused": "no",
        "group_ids": "180,177",
        "category_ids": "1",
        "unit_from_value": "0.50",
        "unit_to_value": "1.00",
        "uom_alternate_name": "Kgs",
        "uom_alternate_id": "2",
        "under_warranty": "no",
        "groupId": "180",
        "catId": "1",
        "prodHsnId": "",
        "prodHsnCode": "",
        "prodShortName": "",
        "prodPrice": "28500.00",
        "prodMrp": "28500.00",
        "prodBuy": "28500.00",
        "prodSell": "28500.00",
        "prodFreeItem": "",
        "prodRkPrice": "28500.00"
      }
    ]
  }
}
*/

  bool? status;
  String? message;
  ProductGetResponseData? data;

  ProductGetResponse({
    this.status,
    this.message,
    this.data,
  });
  ProductGetResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? ProductGetResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
